framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - validation
                 #   - doctrine_transaction
                 #   - dispatch_after_current_bus
            query.bus:
                middleware:
                    - validation
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - validation

        transports:
            async: enqueue://default

        routing:
            '*': async