name: PHP CS Fixer checks

on:
    push

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: ['7.4', '8.0']

        name: PHP ${{ matrix.php-version }} Test

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up PHP
                uses: shivammathur/setup-php@master
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: mbstring, pdo_pgsql, bcmath, amqp, mongodb
                    tools: cs2pr

            -   uses: actions/cache@v2
                with:
                    path: |
                        ~/.composer/cache
                        vendor
                    key: ${{ runner.os }}-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-${{ matrix.php-version }}-composer-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress --ansi

            -   name: PHP CS Fixer checks
                run: vendor/bin/php-cs-fixer fix --verbose --config=.php_cs.php --dry-run --format=checkstyle | cs2pr